### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by tusharsadhwani** [cloudagon/prey#1]
```
$ pip install prey               
ERROR: Could not find a version that satisfies the requirement prey (from versions: none)
ERROR: No matching distribution found for prey
```

Tested on linux on Python 3.8.5

**Comment by tusharsadhwani** [comment]
nevermind, seems to work on 3.9.
although 3.9 is fairly new so might want to look into that.

**Comment by sachinraja** [comment]
I've lowered the requirement to 3.7 in 51db7f249177de37a2039df1b0a7f1956368bc25.
