### ISSUE TITLE
Unable to run a basic example

### ISSUE THREAD

**Issue by tusharsadhwani** [cloudagon/prey#2]
First of all, hi!

Nice work there, I see that you're trying to replicate more of the behaviours and style of zx, and I can appreciate that.

Apart from that, I do have a bug report to file. This is me trying to run prey locally, and it seems you have a packaging issue:

```console
tushar@pop-os:/tmp$ mkdir test && cd test
tushar@pop-os:/tmp/test$ virtualenv venv -p=python3.9
created virtual environment CPython3.9.5.final.0-64 in 156ms
...
tushar@pop-os:/tmp/test$ . venv/bin/activate
(venv) tushar@pop-os:/tmp/test$ pip install prey
Collecting prey
  [...]
Successfully installed aiodns-3.0.0 aiohttp-3.7.4.post0 aiohttp-requests-0.1.3 async-timeout-3.0.1 attrs-21.2.0 cchardet-2.1.7 cffi-1.14.5 chardet-4.0.0 colorama-0.4.4 idna-3.1 multidict-5.1.0 prey-0.1.2 pycares-4.0.0 pycparser-2.20 typing-extensions-3.10.0.0 yarl-1.6.3
(venv) tushar@pop-os:/tmp/test$ echo '
#!/usr/bin/env prey

async def main():
    await _("echo test")
' > test.py
(venv) tushar@pop-os:/tmp/test$ chmod +x ./test.py 
(venv) tushar@pop-os:/tmp/test$ ./test.py 
Traceback (most recent call last):
  File "/tmp/test/venv/bin/prey", line 5, in <module>
    from bin.prey import main
ModuleNotFoundError: No module named 'bin'
(venv) tushar@pop-os:/tmp/test$ 
```

P.S.: The usage of `_` as the canonical variable might be an issue :sweat_smile: because Python uses the `_` variable in the REPL:

```pycon
>>> def x(): return 42
>>> x()
42
>>> print(_)
42
```

So the current syntax might just not work in the REPL at all.

**Comment by sachinraja** [comment]
Ah, looks like it wasn't packaging the `bin` folder. Thanks for letting me know about that. Are there any characters you suggest I use in place of the `_`?

**Comment by tusharsadhwani** [comment]
I don't know, `_` might have been a good choice if Python didn't use it internally. And Python variable names can't be special characters. The only option you have is a regular English character, or an emoji :p

maybe consider `q` or `x`, but honestly I'm not sure. This is one of the reasons why I went with AST parsing in zxpy.

**Comment by sachinraja** [comment]
Ah, didn't realize you were the author of zxpy, your package is awesome! AST parsing is a much better solution but I honestly did not want to mess with all of that. I'll replace it with a single character for now.
